### ISSUE TITLE
Leaflet on navbar should do nothing or link to a general leaflet page

### ISSUE THREAD

**Issue by allc** [hrybrn/ecssweb#22]
it is weird to link to homepage now...

**Comment by hrybrn** [comment]
just change the link to '#' and it should be fine right?

**Comment by allc** [comment]
good thinking! However there is `$relPath` added in the link (and will be `#lang=...` at the end), maybe there is a way generates more elegant html code.

**Comment by hrybrn** [comment]
Ricki says there should be a general page

**Comment by hrybrn** [comment]
hes made some content and I'll give it to you guys when I resurrect

**Comment by allc** [comment]
Rearranged Nav bar, so no leaflet general page issues
